version: '3.8'

services:

  restapi:
    container_name: restapi_cnt
    build: 
      context: .
      dockerfile: resthttp/Dockerfile
    ports:
      - "7001:7001"
    # networks:
    #   - genui-net
    ### !!!! TODO: OVO U PG DOLE!!!
    volumes:
      - pgdbvol:/var/lib/posgresql/data
    environment:
      - DB_HOST=pgdb
      - DB_PORT=5432
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_NAME=genuidb
    depends_on:
      - pgdb

  pgdb:
    container_name: pgdb_cnt
    image: postgres:15.2-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=genuidb
    ports:
      - "5432:5432"
  
  pgadmin:
    container_name: pgadmin_cnt
    image: dpage/pgadmin4:6
    restart: always
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@genui.com
      - PGADMIN_DEFAULT_PASSWORD=r00t
    ports:
      - "7002:80"

  mongo:
    container_name: mongodb_cnt
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongouser
      - MONGO_INITDB_ROOT_PASSWORD=r00t
    ports:
      - "27017:27017"
  
  mongo-express:
    container_name: mongoexpress_cnt
    image: mongo-express
    restart: always
    ports:
      - "7003:8081"
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongo
      - ME_CONFIG_MONGODB_ENABLE_ADMIN=true
      - ME_CONFIG_MONGODB_ADMINUSERNAME=mongouser
      - ME_CONFIG_MONGODB_ADMINPASSWORD=r00t
      - ME_CONFIG_BASICAUTH_USERNAME=expressuser
      - ME_CONFIG_BASICAUTH_PASSWORD=r00t
    depends_on:
      - mongo

volumes:
  pgdbvol:
    driver: local

# networks:
#   genui-net:
#     driver: bridge